# Generated by Django 2.1.4 on 2018-12-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181219_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpis',
            name='obrazek',
            field=models.ImageField(blank=True, upload_to='obrazki_do_wpisow/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='wpis',
            name='status',
            field=models.CharField(choices=[('szkic', 'szkic'), ('gotowy', 'gotowy')], default='szkic', max_length=20),
        ),
    ]
