# Generated by Django 2.1.4 on 2018-12-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obrazek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('obrazek', models.ImageField(upload_to='uploded_images/%y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'obrazki',
            },
        ),
    ]
